# 撤销与超时

## 1 取消协程

有时候需要细粒度的控制协程，launch返回的Job提供了cancel方法，可用于取消已经启动的协程。

1. kotlinx.coroutines中的所有suspend函数都可以取消。
2. 但是，如果协程正在运行中，并且不检查取消状态，则它不能被取消(即使调用了cancel)，

## 2 提高协程间的协作能力

在使用协程时，代码应该检查自己是否被已取消了，以及时的响应其他协程。提高协程间的协作能力

有两种方法可以让计算代码变得可以被取消：

1. 定期调用一个挂定函数，比如yield
2. 在协程内明确地检查自己的取消状态，使用isActive属性

## 3 在协程关闭时释放资源

可取消的suspending函数在取消时抛出CancellationException，可以用通常的异常处理方式来处理异常，
并且在必要的时候释放协程中使用的公共资源。

## 4 实现不可取消的协程

任何在finally块中使用暂停函数的操作都会导致CancellationException，因为运行此代码的协程被取消了，通常情况下，这不是问题，
因为所有关闭资源的操作（关闭文件，取消作业或关闭任何类型的通讯通道）通常都是非阻塞的，不涉及任何挂起功能，但是，在罕见的情况下，
如果需要在已取消的协程中使用suspend ，则可以使用`run(NonCancellable) {...}`来包装代码块：

```kotlin
val job = launch {
        try {
            repeat(1000) { i ->
                println("I'm sleeping $i ...")
                delay(500L)
            }
        } finally {
        //使用run和NonCancellable  
            run(NonCancellable) {
                println("I'm running finally")
                delay(1000L)
                println("And I've just delayed for 1 sec because I'm non-cancellable")
            }
        }
    }
```
run在Builders中提供，其作用是：启动一个suspending函数，并暂停当前函数直到该suspending函数执行完毕，并返回结果。

### 5 给协程设计超时

可以给一个协程设置超时时间，给定时间被协程没有执行完毕，将会抛出异常：TimeoutCancellationException